### YamlMime:ManagedReference
apiRules:
  - exclude:
      uidRegex: ^System
      type: Namespace
  - exclude:
      uidRegex: ^UnityEngine\.
      type: Type
  - exclude:
      uidRegex: UxmlFactory$
      type: Type
  - exclude:
      uidRegex: UxmlTraits$
      type: Type
  - include:
      uidRegex: ^RocketshiftStudio\.Shared\.Singleton
      type: Type
  - exclude:
      uidRegex: ^RocketshiftStudio\.Shared
      type: Type
  - exclude:
      uidRegex: Constants$
      type: Type